<a href="https://colab.research.google.com/github/divya-r-kamat/PyTorch/blob/master/Pytorch_torch.max().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook demonstrates the usage of pytorch's max() function, as the name depicts we can say that this function return's maximum element from the given tensor. 

In [1]:
import torch

In [2]:
p = torch.randn([2, 3])
print(p)

 


tensor([[ 2.6088, -0.0161, -1.1440],
        [-0.5904, -1.5690,  0.7700]])


In [3]:
torch.max(p)

tensor(2.6088)

In [4]:
# Get the maximum along dim = 0 (axis = 0) - Maximum along columns
max_elements, max_idxs = torch.max(p, dim=0)
print(max_elements)
print(max_idxs)

tensor([ 2.6088, -0.0161,  0.7700])
tensor([0, 0, 1])


In [5]:
# Get the maximum along dim = 1 (axis = 1) - Maximum along rows
max_elements, max_idxs = torch.max(p, dim=1)
print(max_elements)
print(max_idxs)

tensor([2.6088, 0.7700])
tensor([0, 2])


In [6]:
p = torch.randn([2, 3])
q = torch.randn([2, 3])
 
print("p =", p)
print("q =",q)
 
# Compare elements of p and q and get the maximum
max_elements = torch.max(p, q)
 
print(max_elements)

p = tensor([[-0.7232, -0.6402, -1.2193],
        [ 0.0794,  0.0158,  2.0138]])
q = tensor([[ 1.1492, -0.1400, -0.2463],
        [ 0.3812, -2.1384,  0.5132]])
tensor([[ 1.1492, -0.1400, -0.2463],
        [ 0.3812,  0.0158,  2.0138]])
